version: "3.8"
services:
  authorization:    
    container_name: authorization
    build:      
     context: ./Authorization.Microservice
     dockerfile: Dockerfile
    ports:
      - "1707:80"
    environment:
      "PUBLIC_PORT": "1707"
    depends_on:
     - sqlserver
    networks:
     - microservice_docker_network
  admin:
   container_name: admin
   build:
    context: ./Admin.Microservice
    dockerfile: Dockerfile
   ports:
     - "6117:80"
   environment:
     "PUBLIC_PORT": "6117"
   depends_on:
     - sqlserver
   networks:
     - microservice_docker_network
  user:
   container_name: user
   build:
    context: ./User.Microservice
    dockerfile: Dockerfile
   ports:
    - "7111:80"
   environment:
     "PUBLIC_PORT": "7111"
   depends_on:
     - sqlserver
   networks:
    - microservice_docker_network
  gateway:
   container_name: gateway
   build:
    context: ./Gateway.Microservise
    dockerfile: Dockerfile
   ports:
    - "5343:80"
   links:
    - authorization
    - admin
    - user
   depends_on:
    - authorization
    - admin
    - user
   networks:
    - microservice_docker_network
  rabbitmq:
   container_name: rabbitmq
   image: rabbitmq:3-management
   ports:
    - 5672:5672
    - 15672:15672
   depends_on:
    - authorization
    - admin
    - user
   networks:
    - microservice_docker_network
  sqlserver:
   container_name: sqlserver
   hostname: sqlserver
   image: mcr.microsoft.com/mssql/server:2019-latest
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Daniil_11
    - MSSQL_PID=Express
   ports:
    - 1433:1433
   volumes:
    - ./data:/var/opt/mssql/data
    - ./log:/var/opt/mssql/log
    - ./secrets:/var/opt/mssql/secrets
   networks:
    - microservice_docker_network
networks:
  microservice_docker_network:
    external: true
    driver: bridge