apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: k8s_auth
    env: prod
    owner: DaniilZelenko
spec:
  replicas: 2
  selector:
    matchLabels:
     app: auth
  template:
    metadata:
      labels:
       app: auth
    spec:
      containers:
      - name: auth
        image: minelisovich/auth:latest
        ports:
        - containerPort: 1707 
        env:
        - name: ASPNETCORE_URLS
          value: http://*:1707
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: LoadBalancer
  ports:
  - port: 1707
  selector:
   app: auth
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
