apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq #default dns name????
  labels:
    app: k8s_rabbitmq
    env: prod
    owner: DaniilZelenko
spec:  
  replicas: 2 
  selector:
    matchLabels:
      app: rabbitmq 
  template: 
    metadata:
     labels:
       app: rabbitmq
    spec:
     containers:
       - name : rabbitmq
         image: rabbitmq:3-management
         ports:
         - containerPort: 5672 
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 5672
  selector:
   app: rabbitmq